#!/usr/bin/python
import httplib, urllib, json, cgi, logging
#set up logging info
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
#load configuration file and XMLresponse 
keysFile = open('/usr/lib/cgi-bin/pushover.key')
keys = json.load(keysFile)
keysFile.close()
responseFile = open('/usr/lib/cgi-bin/telApi_response.xml')
responseBody = responseFile.read()
responseFile.close()

logger.info('keys imported successfully')

#use CGI for now, need to update to WSGI
form = cgi.FieldStorage()

#determine if POST data was actually passed
if form.has_key('From'):
    phoneNum = form["From"].value
else:
    phoneNum = 'no form data'
if form.has_key('CallerName'):
    callerName = form["CallerName"].value
else:
    callerName = 'no caller data'
if form.has_key('To'):
    toPhone = form["To"].value
else:
    toPhone = 'no to phone data'
#log call info
logger.info('inbound call ' + phoneNum + ',' + callerName + ',' + toPhone)
#log call to pushover
if form.has_key('From'):
    logger.info('Attempting connection to Pushover API')
    pushoverData = urllib.urlencode({"token": keys['appKey'], "user" : keys['userKey'], "message" : "Mesa Verde Gate Opened! " + callerName})
    conn = httplib.HTTPSConnection("api.pushover.net:443")
    conn.request("POST", "/1/messages.json", pushoverData, {"Content-type":"application/x-www-form-urlencoded" })
    pushResponse = conn.getresponse()
    logger.info('pushover Response: ' + pushResponse.read())
#
#Respond with TelAPI XML response
print "Content-Type: application/xml"
print "\n"
print responseBody 
